//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAV2009_NST_Management.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAV2009_NST_Management.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics NAV Service Management
        ///Created by Kamil Sacek (Kine) 2009.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry value with original folder for Microsoft NAV Service not found. It seems that there is no NAV Server installed on the machine {0}..
        /// </summary>
        internal static string CannotReadOrigPath {
            get {
                return ResourceManager.GetString("CannotReadOrigPath", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document1 {
            get {
                object obj = ResourceManager.GetObject("document1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_11 {
            get {
                object obj = ResourceManager.GetObject("gear_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New NAV Service Tier was created sucessfully..
        /// </summary>
        internal static string NSTCreated {
            get {
                return ResourceManager.GetString("NSTCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAV ServiceTier was not created. Return code was {0}..
        /// </summary>
        internal static string NSTFailed {
            get {
                return ResourceManager.GetString("NSTFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} not found. May be you have moved it somewhere else (e.g. by Freddy&apos;s batch files)..
        /// </summary>
        internal static string OrigPathNotFound {
            get {
                return ResourceManager.GetString("OrigPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Original folder.
        /// </summary>
        internal static string RedingOrigPath {
            get {
                return ResourceManager.GetString("RedingOrigPath", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RefreshDocViewHS1 {
            get {
                object obj = ResourceManager.GetObject("RefreshDocViewHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Run1 {
            get {
                object obj = ResourceManager.GetObject("Run1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon servicepaused1 {
            get {
                object obj = ResourceManager.GetObject("servicepaused1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon servicerunning1 {
            get {
                object obj = ResourceManager.GetObject("servicerunning1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon servicestopped1 {
            get {
                object obj = ResourceManager.GetObject("servicestopped1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon serviceunknown1 {
            get {
                object obj = ResourceManager.GetObject("serviceunknown1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was not started. 
        ///Reason: {0}.
        /// </summary>
        internal static string StartFailed {
            get {
                return ResourceManager.GetString("StartFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop1 {
            get {
                object obj = ResourceManager.GetObject("Stop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New NAV WebService was created sucessfully..
        /// </summary>
        internal static string WSCreated {
            get {
                return ResourceManager.GetString("WSCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAV WebService was not created. Return code was {0}..
        /// </summary>
        internal static string WSFailed {
            get {
                return ResourceManager.GetString("WSFailed", resourceCulture);
            }
        }
    }
}
